# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myDialogSignalChange.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_myDialogSignalChange(object):
    def setupUi(self, myDialogSignalChange):
        myDialogSignalChange.setObjectName("myDialogSignalChange")
        myDialogSignalChange.resize(651, 397)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(myDialogSignalChange.sizePolicy().hasHeightForWidth())
        myDialogSignalChange.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(myDialogSignalChange)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_6 = QtWidgets.QLabel(myDialogSignalChange)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.LineEdit_belonged = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_belonged.setReadOnly(True)
        self.LineEdit_belonged.setObjectName("LineEdit_belonged")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_belonged)
        self.verticalLayout.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.iDLabel = QtWidgets.QLabel(myDialogSignalChange)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.LineEdit_channelID = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_channelID.setObjectName("LineEdit_channelID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelID)
        self.Label = QtWidgets.QLabel(myDialogSignalChange)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit_channelName = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_channelName.setObjectName("LineEdit_channelName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelName)
        self.Label_2 = QtWidgets.QLabel(myDialogSignalChange)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_usable = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_usable.setObjectName("LineEdit_usable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_usable)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_3 = QtWidgets.QLabel(myDialogSignalChange)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_channelCode = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_channelCode.setObjectName("LineEdit_channelCode")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelCode)
        self.Label_4 = QtWidgets.QLabel(myDialogSignalChange)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_signalType = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_signalType.setObjectName("LineEdit_signalType")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_signalType)
        self.Label_5 = QtWidgets.QLabel(myDialogSignalChange)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_multiple = QtWidgets.QLineEdit(myDialogSignalChange)
        self.LineEdit_multiple.setObjectName("LineEdit_multiple")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_multiple)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_save = QtWidgets.QPushButton(myDialogSignalChange)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(myDialogSignalChange)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(myDialogSignalChange)
        QtCore.QMetaObject.connectSlotsByName(myDialogSignalChange)

    def retranslateUi(self, myDialogSignalChange):
        _translate = QtCore.QCoreApplication.translate
        myDialogSignalChange.setWindowTitle(_translate("myDialogSignalChange", "修改测点配置信息"))
        self.Label_6.setText(_translate("myDialogSignalChange", "所属设备："))
        self.iDLabel.setText(_translate("myDialogSignalChange", "通道ID:"))
        self.Label.setText(_translate("myDialogSignalChange", "通道名称："))
        self.Label_2.setText(_translate("myDialogSignalChange", "是否使用"))
        self.Label_3.setText(_translate("myDialogSignalChange", "通道编码："))
        self.Label_4.setText(_translate("myDialogSignalChange", "信号类型："))
        self.Label_5.setText(_translate("myDialogSignalChange", "放大倍数："))
        self.pushButton_save.setText(_translate("myDialogSignalChange", "保存"))
        self.pushButton_cancel.setText(_translate("myDialogSignalChange", "取消"))

