# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myDialogSignalAdd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_myDialogSignalAdd(object):
    def setupUi(self, myDialogSignalAdd):
        myDialogSignalAdd.setObjectName("myDialogSignalAdd")
        myDialogSignalAdd.resize(651, 397)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(myDialogSignalAdd.sizePolicy().hasHeightForWidth())
        myDialogSignalAdd.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(myDialogSignalAdd)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label_7 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.LineEdit_belonged = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_belonged.setObjectName("LineEdit_belonged")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_belonged)
        self.iDLabel = QtWidgets.QLabel(myDialogSignalAdd)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.LineEdit_channelID = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_channelID.setObjectName("LineEdit_channelID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelID)
        self.Label = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit_channelName = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_channelName.setObjectName("LineEdit_channelName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelName)
        self.Label_2 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_usable = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_usable.setObjectName("LineEdit_usable")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_usable)
        self.Label_6 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_6.setObjectName("Label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.ComboBox_system = QtWidgets.QComboBox(myDialogSignalAdd)
        self.ComboBox_system.setObjectName("ComboBox_system")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ComboBox_system)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_3 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_channelCode = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_channelCode.setObjectName("LineEdit_channelCode")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_channelCode)
        self.Label_4 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_signalType = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_signalType.setObjectName("LineEdit_signalType")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_signalType)
        self.Label_5 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_multiple = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_multiple.setObjectName("LineEdit_multiple")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_multiple)
        self.Label_8 = QtWidgets.QLabel(myDialogSignalAdd)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.LineEdit_unit = QtWidgets.QLineEdit(myDialogSignalAdd)
        self.LineEdit_unit.setObjectName("LineEdit_unit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_unit)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_save = QtWidgets.QPushButton(myDialogSignalAdd)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(myDialogSignalAdd)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(myDialogSignalAdd)
        QtCore.QMetaObject.connectSlotsByName(myDialogSignalAdd)

    def retranslateUi(self, myDialogSignalAdd):
        _translate = QtCore.QCoreApplication.translate
        myDialogSignalAdd.setWindowTitle(_translate("myDialogSignalAdd", "增加测点配置信息"))
        self.Label_7.setText(_translate("myDialogSignalAdd", "所属设备:"))
        self.iDLabel.setText(_translate("myDialogSignalAdd", "通道ID:"))
        self.Label.setText(_translate("myDialogSignalAdd", "通道名称："))
        self.Label_2.setText(_translate("myDialogSignalAdd", "是否使用:"))
        self.Label_6.setText(_translate("myDialogSignalAdd", "所属一级系统"))
        self.Label_3.setText(_translate("myDialogSignalAdd", "通道编码："))
        self.Label_4.setText(_translate("myDialogSignalAdd", "信号类型："))
        self.Label_5.setText(_translate("myDialogSignalAdd", "放大倍数："))
        self.Label_8.setText(_translate("myDialogSignalAdd", "所属机组:"))
        self.pushButton_save.setText(_translate("myDialogSignalAdd", "保存"))
        self.pushButton_cancel.setText(_translate("myDialogSignalAdd", "取消"))

