# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLogo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainLogo.sizePolicy().hasHeightForWidth())
        self.mainLogo.setSizePolicy(sizePolicy)
        self.mainLogo.setMinimumSize(QtCore.QSize(100, 100))
        self.mainLogo.setMaximumSize(QtCore.QSize(100, 100))
        self.mainLogo.setBaseSize(QtCore.QSize(150, 150))
        self.mainLogo.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.mainLogo.setText("")
        self.mainLogo.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/风力发电.png"))
        self.mainLogo.setObjectName("mainLogo")
        self.horizontalLayout.addWidget(self.mainLogo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_20.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab1_6 = QtWidgets.QWidget()
        self.tab1_6.setObjectName("tab1_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab1_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableView_windPowerStation = QtWidgets.QTableView(self.tab1_6)
        self.tableView_windPowerStation.setObjectName("tableView_windPowerStation")
        self.gridLayout_8.addWidget(self.tableView_windPowerStation, 0, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem1, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab1_6)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 2, 0, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab1_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 4, 0, 1, 1)
        self.lineEdit_groupCompany = QtWidgets.QLineEdit(self.tab1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_groupCompany.sizePolicy().hasHeightForWidth())
        self.lineEdit_groupCompany.setSizePolicy(sizePolicy)
        self.lineEdit_groupCompany.setReadOnly(True)
        self.lineEdit_groupCompany.setObjectName("lineEdit_groupCompany")
        self.gridLayout_8.addWidget(self.lineEdit_groupCompany, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab1_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 5, 0, 1, 1)
        self.lineEdit_windField = QtWidgets.QLineEdit(self.tab1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_windField.sizePolicy().hasHeightForWidth())
        self.lineEdit_windField.setSizePolicy(sizePolicy)
        self.lineEdit_windField.setReadOnly(True)
        self.lineEdit_windField.setObjectName("lineEdit_windField")
        self.gridLayout_8.addWidget(self.lineEdit_windField, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab1_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 6, 0, 1, 1)
        self.lineEdit_grossInstalledCapacity = QtWidgets.QLineEdit(self.tab1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_grossInstalledCapacity.sizePolicy().hasHeightForWidth())
        self.lineEdit_grossInstalledCapacity.setSizePolicy(sizePolicy)
        self.lineEdit_grossInstalledCapacity.setReadOnly(True)
        self.lineEdit_grossInstalledCapacity.setObjectName("lineEdit_grossInstalledCapacity")
        self.gridLayout_8.addWidget(self.lineEdit_grossInstalledCapacity, 6, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab1_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 7, 0, 1, 1)
        self.lineEdit_numOfInstalledStations = QtWidgets.QLineEdit(self.tab1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_numOfInstalledStations.sizePolicy().hasHeightForWidth())
        self.lineEdit_numOfInstalledStations.setSizePolicy(sizePolicy)
        self.lineEdit_numOfInstalledStations.setReadOnly(True)
        self.lineEdit_numOfInstalledStations.setClearButtonEnabled(False)
        self.lineEdit_numOfInstalledStations.setObjectName("lineEdit_numOfInstalledStations")
        self.gridLayout_8.addWidget(self.lineEdit_numOfInstalledStations, 7, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(616, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 7, 2, 1, 1)
        self.pushButton_alterA1 = QtWidgets.QPushButton(self.tab1_6)
        self.pushButton_alterA1.setObjectName("pushButton_alterA1")
        self.gridLayout_8.addWidget(self.pushButton_alterA1, 7, 3, 1, 1)
        self.pushButton_closeA1 = QtWidgets.QPushButton(self.tab1_6)
        self.pushButton_closeA1.setObjectName("pushButton_closeA1")
        self.gridLayout_8.addWidget(self.pushButton_closeA1, 7, 4, 1, 1)
        self.tabWidget_2.addTab(self.tab1_6, "")
        self.tab1_2 = QtWidgets.QWidget()
        self.tab1_2.setObjectName("tab1_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab1_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_10.addWidget(self.pushButton_19, 5, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(547, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 4, 6, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_10.addWidget(self.pushButton_18, 5, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem5, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab1_2)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_10.addWidget(self.line_5, 2, 0, 1, 7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem6, 3, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.Label_12 = QtWidgets.QLabel(self.tab1_2)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.LineEdit_12 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_12.sizePolicy().hasHeightForWidth())
        self.LineEdit_12.setSizePolicy(sizePolicy)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_12)
        self.Label_13 = QtWidgets.QLabel(self.tab1_2)
        self.Label_13.setObjectName("Label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.LineEdit_13 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_13.sizePolicy().hasHeightForWidth())
        self.LineEdit_13.setSizePolicy(sizePolicy)
        self.LineEdit_13.setObjectName("LineEdit_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_13)
        self.Label_14 = QtWidgets.QLabel(self.tab1_2)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.LineEdit_14 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_14.sizePolicy().hasHeightForWidth())
        self.LineEdit_14.setSizePolicy(sizePolicy)
        self.LineEdit_14.setObjectName("LineEdit_14")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_14)
        self.Label_15 = QtWidgets.QLabel(self.tab1_2)
        self.Label_15.setObjectName("Label_15")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.LineEdit_15 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_15.sizePolicy().hasHeightForWidth())
        self.LineEdit_15.setSizePolicy(sizePolicy)
        self.LineEdit_15.setObjectName("LineEdit_15")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_15)
        self.Label_16 = QtWidgets.QLabel(self.tab1_2)
        self.Label_16.setObjectName("Label_16")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_16)
        self.LineEdit_16 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_16.sizePolicy().hasHeightForWidth())
        self.LineEdit_16.setSizePolicy(sizePolicy)
        self.LineEdit_16.setObjectName("LineEdit_16")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_16)
        self.gridLayout_10.addLayout(self.formLayout_5, 4, 3, 1, 3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.Label_5 = QtWidgets.QLabel(self.tab1_2)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_5 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_5.sizePolicy().hasHeightForWidth())
        self.LineEdit_5.setSizePolicy(sizePolicy)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.Label_6 = QtWidgets.QLabel(self.tab1_2)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_6.sizePolicy().hasHeightForWidth())
        self.LineEdit_6.setSizePolicy(sizePolicy)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_6)
        self.Label_7 = QtWidgets.QLabel(self.tab1_2)
        self.Label_7.setObjectName("Label_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.LineEdit_7 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_7.sizePolicy().hasHeightForWidth())
        self.LineEdit_7.setSizePolicy(sizePolicy)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_7)
        self.Label_8 = QtWidgets.QLabel(self.tab1_2)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.LineEdit_8 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_8.sizePolicy().hasHeightForWidth())
        self.LineEdit_8.setSizePolicy(sizePolicy)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_8)
        self.Label_9 = QtWidgets.QLabel(self.tab1_2)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.LineEdit_9 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_9.sizePolicy().hasHeightForWidth())
        self.LineEdit_9.setSizePolicy(sizePolicy)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_9)
        self.Label_10 = QtWidgets.QLabel(self.tab1_2)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.LineEdit_10 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_10.sizePolicy().hasHeightForWidth())
        self.LineEdit_10.setSizePolicy(sizePolicy)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_10)
        self.Label_11 = QtWidgets.QLabel(self.tab1_2)
        self.Label_11.setObjectName("Label_11")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.LineEdit_11 = QtWidgets.QLineEdit(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_11.sizePolicy().hasHeightForWidth())
        self.LineEdit_11.setSizePolicy(sizePolicy)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit_11)
        self.gridLayout_10.addLayout(self.formLayout_4, 4, 0, 1, 3)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_10.addWidget(self.comboBox_8, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab1_2, "")
        self.tab1_3 = QtWidgets.QWidget()
        self.tab1_3.setObjectName("tab1_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab1_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_29 = QtWidgets.QLabel(self.tab1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 0, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_11.sizePolicy().hasHeightForWidth())
        self.comboBox_11.setSizePolicy(sizePolicy)
        self.comboBox_11.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_11.addWidget(self.comboBox_11, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 0, 2, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_12.sizePolicy().hasHeightForWidth())
        self.comboBox_12.setSizePolicy(sizePolicy)
        self.comboBox_12.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_11.addWidget(self.comboBox_12, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(572, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 0, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 402, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem8, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab1_3, "")
        self.tab1_4 = QtWidgets.QWidget()
        self.tab1_4.setObjectName("tab1_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab1_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_38 = QtWidgets.QLabel(self.tab1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.gridLayout_16.addWidget(self.label_38, 0, 0, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.tab1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_16.sizePolicy().hasHeightForWidth())
        self.comboBox_16.setSizePolicy(sizePolicy)
        self.comboBox_16.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout_16.addWidget(self.comboBox_16, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.gridLayout_16.addWidget(self.label_39, 0, 2, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.tab1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_15.sizePolicy().hasHeightForWidth())
        self.comboBox_15.setSizePolicy(sizePolicy)
        self.comboBox_15.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout_16.addWidget(self.comboBox_15, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem9, 0, 4, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.tab1_4)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_16.addWidget(self.pushButton_25, 0, 5, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.tab1_4)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_16.addWidget(self.pushButton_26, 0, 6, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab1_4)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_16.addWidget(self.pushButton_24, 0, 7, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(225, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem10, 0, 8, 1, 1)
        self.tableView_9 = QtWidgets.QTableView(self.tab1_4)
        self.tableView_9.setObjectName("tableView_9")
        self.gridLayout_16.addWidget(self.tableView_9, 1, 0, 1, 9)
        self.tabWidget_2.addTab(self.tab1_4, "")
        self.tab1_5 = QtWidgets.QWidget()
        self.tab1_5.setObjectName("tab1_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab1_5)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_42 = QtWidgets.QLabel(self.tab1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.gridLayout_17.addWidget(self.label_42, 0, 0, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.tab1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_18.sizePolicy().hasHeightForWidth())
        self.comboBox_18.setSizePolicy(sizePolicy)
        self.comboBox_18.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout_17.addWidget(self.comboBox_18, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName("label_43")
        self.gridLayout_17.addWidget(self.label_43, 0, 2, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.tab1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_17.sizePolicy().hasHeightForWidth())
        self.comboBox_17.setSizePolicy(sizePolicy)
        self.comboBox_17.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout_17.addWidget(self.comboBox_17, 0, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem11, 0, 4, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab1_5)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_17.addWidget(self.pushButton_29, 0, 5, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab1_5)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_17.addWidget(self.pushButton_28, 0, 6, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.tab1_5)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_17.addWidget(self.pushButton_27, 0, 7, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem12, 0, 8, 1, 1)
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab1_5)
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.tableView_15 = QtWidgets.QTableView(self.tab_14)
        self.tableView_15.setObjectName("tableView_15")
        self.gridLayout_19.addWidget(self.tableView_15, 0, 0, 1, 1)
        self.tabWidget_7.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tableView_14 = QtWidgets.QTableView(self.tab_15)
        self.tableView_14.setObjectName("tableView_14")
        self.gridLayout_18.addWidget(self.tableView_14, 0, 0, 1, 1)
        self.tabWidget_7.addTab(self.tab_15, "")
        self.gridLayout_17.addWidget(self.tabWidget_7, 1, 0, 1, 9)
        self.tabWidget_2.addTab(self.tab1_5, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1142, 281))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.unitLogo_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.unitLogo_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitLogo_1.sizePolicy().hasHeightForWidth())
        self.unitLogo_1.setSizePolicy(sizePolicy)
        self.unitLogo_1.setMinimumSize(QtCore.QSize(100, 100))
        self.unitLogo_1.setMaximumSize(QtCore.QSize(150, 150))
        self.unitLogo_1.setText("")
        self.unitLogo_1.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/小风机.png"))
        self.unitLogo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLogo_1.setWordWrap(False)
        self.unitLogo_1.setObjectName("unitLogo_1")
        self.verticalLayout_4.addWidget(self.unitLogo_1)
        self.unitName_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitName_1.sizePolicy().hasHeightForWidth())
        self.unitName_1.setSizePolicy(sizePolicy)
        self.unitName_1.setMinimumSize(QtCore.QSize(0, 0))
        self.unitName_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.unitName_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.unitName_1.setAlignment(QtCore.Qt.AlignCenter)
        self.unitName_1.setObjectName("unitName_1")
        self.verticalLayout_4.addWidget(self.unitName_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.mSLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mSLabel.setObjectName("mSLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mSLabel)
        self.kWLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWLabel.setObjectName("kWLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kWLabel)
        self.Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit.sizePolicy().hasHeightForWidth())
        self.LineEdit.setSizePolicy(sizePolicy)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.kWhDLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWhDLabel.setObjectName("kWhDLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kWhDLabel)
        self.kWhDLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWhDLineEdit.sizePolicy().hasHeightForWidth())
        self.kWhDLineEdit.setSizePolicy(sizePolicy)
        self.kWhDLineEdit.setObjectName("kWhDLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kWhDLineEdit)
        self.mSLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSLineEdit.sizePolicy().hasHeightForWidth())
        self.mSLineEdit.setSizePolicy(sizePolicy)
        self.mSLineEdit.setObjectName("mSLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mSLineEdit)
        self.kWLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWLineEdit.sizePolicy().hasHeightForWidth())
        self.kWLineEdit.setSizePolicy(sizePolicy)
        self.kWLineEdit.setObjectName("kWLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kWLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.gridLayout_21.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.unitLogo_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.unitLogo_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitLogo_5.sizePolicy().hasHeightForWidth())
        self.unitLogo_5.setSizePolicy(sizePolicy)
        self.unitLogo_5.setMinimumSize(QtCore.QSize(100, 100))
        self.unitLogo_5.setMaximumSize(QtCore.QSize(150, 150))
        self.unitLogo_5.setText("")
        self.unitLogo_5.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/小风机.png"))
        self.unitLogo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLogo_5.setWordWrap(False)
        self.unitLogo_5.setObjectName("unitLogo_5")
        self.verticalLayout_23.addWidget(self.unitLogo_5)
        self.unitName_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitName_5.sizePolicy().hasHeightForWidth())
        self.unitName_5.setSizePolicy(sizePolicy)
        self.unitName_5.setMinimumSize(QtCore.QSize(0, 0))
        self.unitName_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.unitName_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.unitName_5.setAlignment(QtCore.Qt.AlignCenter)
        self.unitName_5.setObjectName("unitName_5")
        self.verticalLayout_23.addWidget(self.unitName_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_23)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_13.setObjectName("formLayout_13")
        self.mSLabel_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mSLabel_5.setObjectName("mSLabel_5")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mSLabel_5)
        self.kWLabel_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWLabel_5.setObjectName("kWLabel_5")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kWLabel_5)
        self.Label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_44.setObjectName("Label_44")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_44)
        self.LineEdit_44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_44.sizePolicy().hasHeightForWidth())
        self.LineEdit_44.setSizePolicy(sizePolicy)
        self.LineEdit_44.setObjectName("LineEdit_44")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_44)
        self.kWhDLabel_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWhDLabel_5.setObjectName("kWhDLabel_5")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kWhDLabel_5)
        self.kWhDLineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWhDLineEdit_5.sizePolicy().hasHeightForWidth())
        self.kWhDLineEdit_5.setSizePolicy(sizePolicy)
        self.kWhDLineEdit_5.setObjectName("kWhDLineEdit_5")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kWhDLineEdit_5)
        self.mSLineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSLineEdit_5.sizePolicy().hasHeightForWidth())
        self.mSLineEdit_5.setSizePolicy(sizePolicy)
        self.mSLineEdit_5.setObjectName("mSLineEdit_5")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mSLineEdit_5)
        self.kWLineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWLineEdit_5.sizePolicy().hasHeightForWidth())
        self.kWLineEdit_5.setSizePolicy(sizePolicy)
        self.kWLineEdit_5.setObjectName("kWLineEdit_5")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kWLineEdit_5)
        self.horizontalLayout_8.addLayout(self.formLayout_13)
        self.gridLayout_21.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(243, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem13, 0, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.unitLogo_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.unitLogo_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitLogo_6.sizePolicy().hasHeightForWidth())
        self.unitLogo_6.setSizePolicy(sizePolicy)
        self.unitLogo_6.setMinimumSize(QtCore.QSize(100, 100))
        self.unitLogo_6.setMaximumSize(QtCore.QSize(150, 150))
        self.unitLogo_6.setText("")
        self.unitLogo_6.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/小风机.png"))
        self.unitLogo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLogo_6.setWordWrap(False)
        self.unitLogo_6.setObjectName("unitLogo_6")
        self.verticalLayout_24.addWidget(self.unitLogo_6)
        self.unitName_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitName_6.sizePolicy().hasHeightForWidth())
        self.unitName_6.setSizePolicy(sizePolicy)
        self.unitName_6.setMinimumSize(QtCore.QSize(0, 0))
        self.unitName_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.unitName_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.unitName_6.setAlignment(QtCore.Qt.AlignCenter)
        self.unitName_6.setObjectName("unitName_6")
        self.verticalLayout_24.addWidget(self.unitName_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_24)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setObjectName("formLayout_14")
        self.mSLabel_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mSLabel_6.setObjectName("mSLabel_6")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mSLabel_6)
        self.kWLabel_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWLabel_6.setObjectName("kWLabel_6")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kWLabel_6)
        self.Label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_45.setObjectName("Label_45")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_45)
        self.LineEdit_45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_45.sizePolicy().hasHeightForWidth())
        self.LineEdit_45.setSizePolicy(sizePolicy)
        self.LineEdit_45.setObjectName("LineEdit_45")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_45)
        self.kWhDLabel_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWhDLabel_6.setObjectName("kWhDLabel_6")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kWhDLabel_6)
        self.kWhDLineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWhDLineEdit_6.sizePolicy().hasHeightForWidth())
        self.kWhDLineEdit_6.setSizePolicy(sizePolicy)
        self.kWhDLineEdit_6.setObjectName("kWhDLineEdit_6")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kWhDLineEdit_6)
        self.mSLineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSLineEdit_6.sizePolicy().hasHeightForWidth())
        self.mSLineEdit_6.setSizePolicy(sizePolicy)
        self.mSLineEdit_6.setObjectName("mSLineEdit_6")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mSLineEdit_6)
        self.kWLineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWLineEdit_6.sizePolicy().hasHeightForWidth())
        self.kWLineEdit_6.setSizePolicy(sizePolicy)
        self.kWLineEdit_6.setObjectName("kWLineEdit_6")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kWLineEdit_6)
        self.horizontalLayout_9.addLayout(self.formLayout_14)
        self.gridLayout_21.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.unitLogo_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.unitLogo_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitLogo_7.sizePolicy().hasHeightForWidth())
        self.unitLogo_7.setSizePolicy(sizePolicy)
        self.unitLogo_7.setMinimumSize(QtCore.QSize(100, 100))
        self.unitLogo_7.setMaximumSize(QtCore.QSize(150, 150))
        self.unitLogo_7.setText("")
        self.unitLogo_7.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/小风机.png"))
        self.unitLogo_7.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLogo_7.setWordWrap(False)
        self.unitLogo_7.setObjectName("unitLogo_7")
        self.verticalLayout_25.addWidget(self.unitLogo_7)
        self.unitName_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitName_7.sizePolicy().hasHeightForWidth())
        self.unitName_7.setSizePolicy(sizePolicy)
        self.unitName_7.setMinimumSize(QtCore.QSize(0, 0))
        self.unitName_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.unitName_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.unitName_7.setAlignment(QtCore.Qt.AlignCenter)
        self.unitName_7.setObjectName("unitName_7")
        self.verticalLayout_25.addWidget(self.unitName_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_25)
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_15.setObjectName("formLayout_15")
        self.mSLabel_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mSLabel_7.setObjectName("mSLabel_7")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mSLabel_7)
        self.kWLabel_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWLabel_7.setObjectName("kWLabel_7")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kWLabel_7)
        self.Label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label_46.setObjectName("Label_46")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_46)
        self.LineEdit_46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_46.sizePolicy().hasHeightForWidth())
        self.LineEdit_46.setSizePolicy(sizePolicy)
        self.LineEdit_46.setObjectName("LineEdit_46")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_46)
        self.kWhDLabel_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.kWhDLabel_7.setObjectName("kWhDLabel_7")
        self.formLayout_15.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kWhDLabel_7)
        self.kWhDLineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWhDLineEdit_7.sizePolicy().hasHeightForWidth())
        self.kWhDLineEdit_7.setSizePolicy(sizePolicy)
        self.kWhDLineEdit_7.setObjectName("kWhDLineEdit_7")
        self.formLayout_15.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kWhDLineEdit_7)
        self.mSLineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mSLineEdit_7.sizePolicy().hasHeightForWidth())
        self.mSLineEdit_7.setSizePolicy(sizePolicy)
        self.mSLineEdit_7.setObjectName("mSLineEdit_7")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mSLineEdit_7)
        self.kWLineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kWLineEdit_7.sizePolicy().hasHeightForWidth())
        self.kWLineEdit_7.setSizePolicy(sizePolicy)
        self.kWLineEdit_7.setObjectName("kWLineEdit_7")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kWLineEdit_7)
        self.horizontalLayout_10.addLayout(self.formLayout_15)
        self.gridLayout_21.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.unitDetalFrame = QtWidgets.QFrame(self.tab2)
        self.unitDetalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.unitDetalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.unitDetalFrame.setObjectName("unitDetalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.unitDetalFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_3)
        self.Label_2 = QtWidgets.QLabel(self.unitDetalFrame)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.unitDetalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_2.sizePolicy().hasHeightForWidth())
        self.LineEdit_2.setSizePolicy(sizePolicy)
        self.LineEdit_2.setMinimumSize(QtCore.QSize(150, 0))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.unitDetalFrame)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.unitDetalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_3.sizePolicy().hasHeightForWidth())
        self.LineEdit_3.setSizePolicy(sizePolicy)
        self.LineEdit_3.setMinimumSize(QtCore.QSize(150, 0))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_4 = QtWidgets.QLabel(self.unitDetalFrame)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.unitDetalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_4.sizePolicy().hasHeightForWidth())
        self.LineEdit_4.setSizePolicy(sizePolicy)
        self.LineEdit_4.setMinimumSize(QtCore.QSize(150, 0))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.unitDetalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem14 = QtWidgets.QSpacerItem(20, 183, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem14, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(750, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem15, 1, 0, 1, 1)
        self.backT = QtWidgets.QPushButton(self.tab)
        self.backT.setObjectName("backT")
        self.gridLayout_22.addWidget(self.backT, 1, 1, 1, 1)
        self.backT.raise_()
        self.tabWidget_3.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 3, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_8.addWidget(self.comboBox_2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem18)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_9.addWidget(self.dateEdit)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_9.addWidget(self.dateEdit_2)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.verticalLayout_9.addWidget(self.dateEdit_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem19)
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem20)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setText("返回主界面")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_12.addWidget(self.pushButton_3)
        self.gridLayout_3.addWidget(self.frame_5, 2, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_3)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 100))
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 100))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem21 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.gridLayout_2.addWidget(self.frame_4, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.tabWidget_3.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget_3, 0, 1, 2, 1)
        self.treeView_unit = QtWidgets.QTreeView(self.unitDetalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeView_unit.sizePolicy().hasHeightForWidth())
        self.treeView_unit.setSizePolicy(sizePolicy)
        self.treeView_unit.setObjectName("treeView_unit")
        self.gridLayout.addWidget(self.treeView_unit, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.unitDetalFrame)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab3)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/Charming/.designer/backup/pic/小风机.png"))
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_6)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_14.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_14.addWidget(self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_14.addWidget(self.comboBox_4)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_14.addWidget(self.comboBox_5)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem23)
        self.label_8.raise_()
        self.comboBox_4.raise_()
        self.label_6.raise_()
        self.comboBox_5.raise_()
        self.comboBox_3.raise_()
        self.label_7.raise_()
        self.gridLayout_4.addWidget(self.frame_6, 0, 1, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(200, 30, 341, 211))
        self.widget_4.setObjectName("widget_4")
        self.tabWidget_4.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setGeometry(QtCore.QRect(190, 20, 411, 241))
        self.widget_5.setObjectName("widget_5")
        self.tabWidget_4.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.tabWidget_4, 1, 0, 1, 2)
        self.verticalLayout_17.addLayout(self.gridLayout_4)
        self.tabWidget_5.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 4, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 6, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_7)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 2, 0, 1, 3)
        self.tableView = QtWidgets.QTableView(self.tab_7)
        self.tableView.setObjectName("tableView")
        self.gridLayout_5.addWidget(self.tableView, 1, 0, 1, 3)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 5, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 5, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem24)
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_4.addWidget(self.comboBox_6)
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_4.addWidget(self.comboBox_7)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem25)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit.setSizePolicy(sizePolicy)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit)
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_2.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_2.setSizePolicy(sizePolicy)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.tabWidget_5.addTab(self.tab_7, "")
        self.verticalLayout_16.addWidget(self.tabWidget_5)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setEnabled(True)
        self.tab4.setObjectName("tab4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 1, 1, 1, 3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 2, 1, 1, 3)
        self.treeView_fault = QtWidgets.QTreeView(self.tab4)
        self.treeView_fault.setObjectName("treeView_fault")
        self.gridLayout_6.addWidget(self.treeView_fault, 0, 0, 1, 4)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_6.addWidget(self.pushButton_11, 3, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tab4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab4)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_6.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab4)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_6.addWidget(self.pushButton_13, 3, 3, 1, 1)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab4)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.tab_8)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_7.addWidget(self.tableView_2, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_8)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 3, 0, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(self.tab_8)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_7.addWidget(self.tableView_3, 4, 0, 1, 1)
        self.tabWidget_6.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableView_4 = QtWidgets.QTableView(self.tab_9)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_10.addWidget(self.tableView_4)
        self.tabWidget_6.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableView_5 = QtWidgets.QTableView(self.tab_10)
        self.tableView_5.setObjectName("tableView_5")
        self.verticalLayout_15.addWidget(self.tableView_5)
        self.tabWidget_6.addTab(self.tab_10, "")
        self.gridLayout_6.addWidget(self.tabWidget_6, 0, 4, 4, 1)
        self.tabWidget.addTab(self.tab4, "")
        self.gridLayout_20.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "知识库"))
        self.pushButton_2.setText(_translate("MainWindow", "系统登入"))
        self.label_19.setText(_translate("MainWindow", "集团名称："))
        self.label_20.setText(_translate("MainWindow", "风场位置："))
        self.label_21.setText(_translate("MainWindow", "总装机容量（kW）："))
        self.label_22.setText(_translate("MainWindow", "装机台数"))
        self.pushButton_alterA1.setText(_translate("MainWindow", "修改"))
        self.pushButton_closeA1.setText(_translate("MainWindow", "关闭"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab1_6), _translate("MainWindow", "风电场信息"))
        self.pushButton_19.setText(_translate("MainWindow", "修改"))
        self.pushButton_18.setText(_translate("MainWindow", "关闭"))
        self.label_23.setText(_translate("MainWindow", "集团名称："))
        self.Label_12.setText(_translate("MainWindow", "姓名："))
        self.Label_13.setText(_translate("MainWindow", "工号："))
        self.Label_14.setText(_translate("MainWindow", "工作电话："))
        self.Label_15.setText(_translate("MainWindow", "岗位："))
        self.Label_16.setText(_translate("MainWindow", "所属部门："))
        self.Label_5.setText(_translate("MainWindow", "风机型号："))
        self.Label_6.setText(_translate("MainWindow", "变频器："))
        self.Label_7.setText(_translate("MainWindow", "齿轮箱："))
        self.Label_8.setText(_translate("MainWindow", "控制系统："))
        self.Label_9.setText(_translate("MainWindow", "发电机："))
        self.Label_10.setText(_translate("MainWindow", "变桨系统："))
        self.Label_11.setText(_translate("MainWindow", "发电机额定转速："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab1_2), _translate("MainWindow", "机组及管辖人员信息"))
        self.label_29.setText(_translate("MainWindow", "机组："))
        self.label_30.setText(_translate("MainWindow", "系统："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab1_3), _translate("MainWindow", "设备信息"))
        self.label_38.setText(_translate("MainWindow", "机组："))
        self.label_39.setText(_translate("MainWindow", "系统："))
        self.pushButton_25.setText(_translate("MainWindow", "添加"))
        self.pushButton_26.setText(_translate("MainWindow", "修改"))
        self.pushButton_24.setText(_translate("MainWindow", "删除"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab1_4), _translate("MainWindow", "测点配置"))
        self.label_42.setText(_translate("MainWindow", "机组："))
        self.label_43.setText(_translate("MainWindow", "系统："))
        self.pushButton_29.setText(_translate("MainWindow", "添加"))
        self.pushButton_28.setText(_translate("MainWindow", "修改"))
        self.pushButton_27.setText(_translate("MainWindow", "删除"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_14), _translate("MainWindow", "残差类"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_15), _translate("MainWindow", "参数趋势类"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab1_5), _translate("MainWindow", "参数配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "系统管理"))
        self.unitName_1.setText(_translate("MainWindow", "1#机组"))
        self.mSLabel.setText(_translate("MainWindow", "风速（m/s)"))
        self.kWLabel.setText(_translate("MainWindow", "功率（kW）"))
        self.Label.setText(_translate("MainWindow", "环境温度（℃）"))
        self.kWhDLabel.setText(_translate("MainWindow", "日发电量（kWh/d）"))
        self.unitName_5.setText(_translate("MainWindow", "1#机组"))
        self.mSLabel_5.setText(_translate("MainWindow", "风速（m/s)"))
        self.kWLabel_5.setText(_translate("MainWindow", "功率（kW）"))
        self.Label_44.setText(_translate("MainWindow", "环境温度（℃）"))
        self.kWhDLabel_5.setText(_translate("MainWindow", "日发电量（kWh/d）"))
        self.unitName_6.setText(_translate("MainWindow", "1#机组"))
        self.mSLabel_6.setText(_translate("MainWindow", "风速（m/s)"))
        self.kWLabel_6.setText(_translate("MainWindow", "功率（kW）"))
        self.Label_45.setText(_translate("MainWindow", "环境温度（℃）"))
        self.kWhDLabel_6.setText(_translate("MainWindow", "日发电量（kWh/d）"))
        self.unitName_7.setText(_translate("MainWindow", "1#机组"))
        self.mSLabel_7.setText(_translate("MainWindow", "风速（m/s)"))
        self.kWLabel_7.setText(_translate("MainWindow", "功率（kW）"))
        self.Label_46.setText(_translate("MainWindow", "环境温度（℃）"))
        self.kWhDLabel_7.setText(_translate("MainWindow", "日发电量（kWh/d）"))
        self.Label_2.setText(_translate("MainWindow", "当前时间："))
        self.Label_3.setText(_translate("MainWindow", "当前机组"))
        self.Label_4.setText(_translate("MainWindow", "当前系统"))
        self.backT.setText(_translate("MainWindow", "返回主界面"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "主检测图"))
        self.label_2.setText(_translate("MainWindow", "通道选择"))
        self.label_3.setText(_translate("MainWindow", "日报："))
        self.label_4.setText(_translate("MainWindow", "月报："))
        self.label_5.setText(_translate("MainWindow", "年报："))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("MainWindow", "趋势图"))
        self.label.setText(_translate("MainWindow", "通道选择"))
        self.pushButton_5.setText(_translate("MainWindow", "返回主界面"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("MainWindow", "波形图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "风电机组实时监测"))
        self.label_6.setText(_translate("MainWindow", "机组选择"))
        self.label_7.setText(_translate("MainWindow", "系统选择"))
        self.label_8.setText(_translate("MainWindow", "通道选择"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4), _translate("MainWindow", "残差图"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("MainWindow", "趋势图"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_6), _translate("MainWindow", "主诊断图"))
        self.label_14.setText(_translate("MainWindow", "征兆"))
        self.pushButton_8.setText(_translate("MainWindow", "图谱"))
        self.pushButton_10.setText(_translate("MainWindow", "图谱"))
        self.pushButton_9.setText(_translate("MainWindow", "图谱"))
        self.label_12.setText(_translate("MainWindow", "机组："))
        self.label_13.setText(_translate("MainWindow", "系统："))
        self.pushButton_6.setText(_translate("MainWindow", "查询"))
        self.pushButton_7.setText(_translate("MainWindow", "维修报表"))
        self.label_10.setText(_translate("MainWindow", "从"))
        self.label_11.setText(_translate("MainWindow", "至"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_7), _translate("MainWindow", "诊断结果与维修决策"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "机组诊断与维修"))
        self.pushButton_11.setText(_translate("MainWindow", "添加"))
        self.label_15.setText(_translate("MainWindow", "当前系统："))
        self.label_16.setText(_translate("MainWindow", "当前故障："))
        self.pushButton_12.setText(_translate("MainWindow", "修改"))
        self.pushButton_13.setText(_translate("MainWindow", "删除"))
        self.label_17.setText(_translate("MainWindow", "预警"))
        self.label_18.setText(_translate("MainWindow", "诊断"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_8), _translate("MainWindow", "征兆规则"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_9), _translate("MainWindow", "原因及措施"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_10), _translate("MainWindow", "故障影响"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "机组故障知识库"))

